import { Company, Client, WeighingRecord, PaymentRecord, InventoryItem, AppNotification, UserProfile } from '../types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp_galpon_real',
    name: 'Avícola El Galpón Real S.A.C.',
    taxId: 'RUC 20601234567',
    phone: '+51 987-654-321',
    address: 'Av. Panamericana Sur Km 35, Lurín, Lima - Perú',
    email: 'contacto@galponreal.com',
    logoUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=300&q=80',
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'comp_aves_valle',
    name: 'Inversiones Aves del Valle S.A.C.',
    taxId: 'RUC 20519876543',
    phone: '+51 912-555-982',
    address: 'Carretera Central Km 18, Ate, Lima',
    email: 'ventas@avesdelvalle.com',
    logoUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=300&q=80',
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_san_juan',
    companyId: 'comp_galpon_real',
    name: 'Distribuidora San Juan',
    phone: '+51 914-998-112',
    email: 'compras@sanjuan.com',
    address: 'Mercado Mayorista Santa Anita, Puesto B-12',
    creditLimit: 10000,
    creditDays: 15,
    currentBalance: 820.50,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cli_don_jose',
    companyId: 'comp_galpon_real',
    name: 'Mercado Central - Don José',
    phone: '+51 926-333-445',
    email: 'donjose@mercadocentral.pe',
    address: 'Av. Tacna 452, Cercado de Lima',
    creditLimit: 5000,
    creditDays: 7,
    currentBalance: 1250.00,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'cli_pollos_express',
    companyId: 'comp_galpon_real',
    name: 'Frigorífico Pollos Express',
    phone: '+51 912-111-223',
    email: 'contacto@pollosexpress.pe',
    address: 'Av. La Marina 1200, San Miguel',
    creditLimit: 15000,
    creditDays: 30,
    currentBalance: 0,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const INITIAL_WEIGHINGS: WeighingRecord[] = [
  {
    id: 'weigh_1001',
    ticketNumber: 'TK-2026-1001',
    companyId: 'comp_galpon_real',
    clientId: 'cli_san_juan',
    clientName: 'Distribuidora San Juan',
    chickenCount: 120,
    grossWeight: 288.0,
    tareWeight: 0,
    netWeight: 288.0,
    unitPrice: 8.50,
    totalAmount: 2448.00,
    paidAmount: 1627.50,
    pendingAmount: 820.50,
    paymentType: 'credito',
    paymentStatus: 'parcial',
    creditDays: 15,
    dueDate: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    notes: 'Despacho matutino directo. Galpón 1 Norte.',
    scaleImageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    galponId: 'inv_1',
    galponName: 'Galpón 1 - Norte (Pollos Broiler)',
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    createdBy: 'Carlos Operario',
  },
  {
    id: 'weigh_1002',
    ticketNumber: 'TK-2026-1002',
    companyId: 'comp_galpon_real',
    clientId: 'cli_don_jose',
    clientName: 'Mercado Central - Don José',
    chickenCount: 180,
    grossWeight: 430.0,
    tareWeight: 0,
    netWeight: 430.0,
    unitPrice: 8.80,
    totalAmount: 3784.00,
    paidAmount: 2534.00,
    pendingAmount: 1250.00,
    paymentType: 'credito',
    paymentStatus: 'parcial',
    creditDays: 7,
    dueDate: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    notes: 'Peso directo de balanza electrónica en Galpón 2',
    scaleImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    galponId: 'inv_2',
    galponName: 'Galpón 2 - Sur (Pollos de Engorde)',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdBy: 'Carlos Operario',
  },
  {
    id: 'weigh_1003',
    ticketNumber: 'TK-2026-1003',
    companyId: 'comp_galpon_real',
    clientId: 'cli_pollos_express',
    clientName: 'Frigorífico Pollos Express',
    chickenCount: 250,
    grossWeight: 600.0,
    tareWeight: 0,
    netWeight: 600.0,
    unitPrice: 8.20,
    totalAmount: 4920.00,
    paidAmount: 4920.00,
    pendingAmount: 0,
    paymentType: 'contado',
    paymentStatus: 'pagado',
    dueDate: new Date().toISOString().split('T')[0],
    notes: 'Pago de contado en efectivo',
    scaleImageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    galponId: 'inv_1',
    galponName: 'Galpón 1 - Norte (Pollos Broiler)',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdBy: 'María Administradora',
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay_1',
    companyId: 'comp_galpon_real',
    clientId: 'cli_san_juan',
    clientName: 'Distribuidora San Juan',
    weighingId: 'weigh_1001',
    ticketNumber: 'TK-2026-1001',
    amount: 500.00,
    method: 'yape',
    reference: 'YAPE-998231',
    voucherUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    notes: 'Abono realizado vía Yape por el cliente',
    status: 'aprobado',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdBy: 'Distribuidora San Juan',
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv_1',
    companyId: 'comp_galpon_real',
    category: 'pollo_vivo',
    name: 'Galpón 1 - Norte (Pollos Broiler)',
    headCount: 2450,
    totalWeight: 5880,
    averageWeight: 2.4,
    unit: 'aves',
    minAlertThreshold: 500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv_2',
    companyId: 'comp_galpon_real',
    category: 'pollo_vivo',
    name: 'Galpón 2 - Sur (Pollos de Engorde)',
    headCount: 3100,
    totalWeight: 5580,
    averageWeight: 1.8,
    unit: 'aves',
    minAlertThreshold: 600,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv_3',
    companyId: 'comp_galpon_real',
    category: 'alimento',
    name: 'Alimento Balanceado Iniciador (Sacos 40kg)',
    headCount: 120,
    totalWeight: 4800,
    averageWeight: 40,
    unit: 'sacos',
    minAlertThreshold: 30,
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    companyId: 'comp_galpon_real',
    targetRole: 'empresa',
    title: '📲 Nuevo Abono Yape del Cliente',
    message: 'Distribuidora San Juan envió un abono de S/ 500.00 por Yape (Comprobante adjunto).',
    type: 'payment',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif_2',
    companyId: 'comp_galpon_real',
    targetRole: 'empresa',
    title: '✅ Pesaje Completado',
    message: 'Nuevo ticket TK-2026-1003 registrado por 250 pollos (600.0 kg).',
    type: 'weighing',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  }
];

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'demo_admin',
    email: 'admin@aviscontrol.com',
    username: 'admin',
    password: '1234',
    displayName: 'Administrador Principal',
    role: 'admin',
    accessLevel: 'super_admin',
    permissions: ['all'],
    phone: '+51 987-654-321',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'demo_empresa',
    email: 'empresa@galponreal.com',
    username: 'empresa',
    password: '1234',
    displayName: 'María Administradora (Galpón Real)',
    role: 'empresa',
    companyId: 'comp_galpon_real',
    accessLevel: 'supervisor',
    permissions: ['manage_clients', 'manage_weighing', 'manage_payments', 'view_reports'],
    phone: '+51 912-555-019',
    createdAt: new Date().toISOString(),
  },
  {
    uid: 'demo_cliente',
    email: 'sanjuan@cliente.com',
    username: 'cliente',
    password: '1234',
    displayName: 'Distribuidora San Juan (Portal Cliente)',
    role: 'cliente',
    companyId: 'comp_galpon_real',
    clientId: 'cli_san_juan',
    accessLevel: 'operador',
    permissions: ['view_own_tickets'],
    phone: '+51 914-998-112',
    createdAt: new Date().toISOString(),
  }
];
